### ISSUE TITLE
S01-1 and S01-3 paragraphs have bottom borders

### ISSUE THREAD

**Issue by mds3dstn71** [mds3dstn71/bryce#12]
A result of the introduction of the cited ruleset below, paragraphs in `S01-1` and `S01-3` have a `1px` bottom border. This border is not undesired in the paragraphs in `S01-2` which is intended to visually separate each _timeline_ entry.

```css
/* main.css@Ln194 */
main p {
  padding-bottom: 13px;
  line-height: 1.125em;
  border-bottom: 1px solid #888;
}
```
